export const AI_ACTIONS = [
  { key: 'bid-no-bid', title: 'Bid / no-bid', phase: 'capture', companyEvidence: 'required', query: 'eligibility set-aside NAICS deadline evaluation scope capacity contract vehicle clearance price', description: 'Score strategic fit, hard stops, conditions, and the next decision gate.', instruction: 'Recommend bid, no-bid, conditional, or insufficient-evidence. Separate hard stops from weighted factors and never manufacture a win probability.' },
  { key: 'eligibility', title: 'Eligibility screen', phase: 'capture', companyEvidence: 'required', query: 'eligibility set-aside NAICS size SAM registration certifications clearance responsibility', description: 'Check every stated eligibility criterion against approved company evidence.', instruction: 'Return explicit pass, fail, or unknown checks. Unknown evidence never becomes a pass. Label this procurement screening, not legal advice.' },
  { key: 'opportunity-fit', title: 'Opportunity fit', phase: 'capture', companyEvidence: 'required', query: 'mission scope objectives technical requirements evaluation priorities staffing security outcomes', description: 'Map capabilities and proof to the opportunity without overstating adjacent experience.', instruction: 'Evaluate fit dimensions, matched capabilities, gaps, and differentiators. Every company strength needs a company citation.' },
  { key: 'win-themes', title: 'Win themes', phase: 'capture', companyEvidence: 'required', query: 'customer need mission objectives evaluation factors outcomes success measures discriminators', description: 'Create evaluator-aligned themes with proof and visible proof gaps.', instruction: 'Create concise customer-need/value/proof themes. Do not use unsupported superlatives or guarantees.' },
  { key: 'requirement-extraction', title: 'Requirement extraction', phase: 'compliance', companyEvidence: 'prohibited', query: 'shall must required deliver submit provide comply deadline frequency acceptance page limit format', description: 'Review machine-extracted obligations and identify missing or compound requirements.', instruction: 'Preserve source wording, distinguish mandatory from optional language, and identify atomic obligations and ambiguities. Do not claim database changes were applied.' },
  { key: 'evaluation-mapping', title: 'Evaluation mapping', phase: 'compliance', companyEvidence: 'prohibited', query: 'Section L Section M evaluation factor subfactor importance weight rating proposal instruction', description: 'Connect evaluation factors, requirements, evidence expectations, and proposal sections.', instruction: 'Never invent weights. Distinguish stated evaluation language from analyst interpretation and identify unmapped requirements.' },
  { key: 'amendment-delta', title: 'Amendment impact', phase: 'sources', companyEvidence: 'prohibited', query: 'added removed revised clarified amendment due date submission evaluation pricing deliverable Q&A', description: 'Compare current and superseded evidence, then identify affected work products.', instruction: 'Identify added, removed, modified, and clarified content. Cite both baseline and current evidence when applicable; removed content cannot support current compliance.' },
  { key: 'risk-register', title: 'Risk register', phase: 'capture', companyEvidence: 'optional', query: 'risk constraint dependency assumption deadline staffing transition security acceptance penalty schedule', description: 'Build sourced and inferred capture/delivery risks with mitigations.', instruction: 'Separate source-based risks from analyst inference. Use qualitative likelihood unless a source provides a probability.' },
  { key: 'capture-strategy', title: 'Capture strategy', phase: 'capture', companyEvidence: 'required', query: 'mission acquisition objectives evaluation priorities timeline stakeholders incumbent transition teaming', description: 'Develop positioning, intelligence gaps, milestones, teaming, and no-bid triggers.', instruction: 'Treat stakeholder and incumbent assertions as hypotheses unless evidenced. Never invent relationships or restricted procurement information.' },
  { key: 'clarification-questions', title: 'Clarification questions', phase: 'capture', companyEvidence: 'optional', query: 'ambiguous undefined conflicting missing attachment date interface volume threshold pricing submission', description: 'Draft neutral source-linked questions without guessing the answer.', instruction: 'Use neutral, non-leading wording. Explain impact and source basis. Never submit questions automatically.' },
  { key: 'pricing-review', title: 'Pricing review', phase: 'review', companyEvidence: 'required', query: 'CLIN pricing schedule quantity option year ceiling total cost realism assumptions travel fee', description: 'Review instruction compliance, assumptions, option years, and price risks.', instruction: 'Do not infer rates or approve price. State that arithmetic must be calculated deterministically and pricing authority approval is required.' },
  { key: 'section-draft', title: 'Proposal section draft', phase: 'proposal', companyEvidence: 'required', query: 'technical management deliverables evaluation requirements approach outcomes evidence', description: 'Draft a traceable section with evidence gaps instead of invented company claims.', instruction: 'Draft professional prose using only supplied evidence. Use [COMPANY EVIDENCE NEEDED: …] for missing proof and label the output as a draft.' },
  { key: 'color-team-review', title: 'Color-team review', phase: 'review', companyEvidence: 'required', query: 'evaluation factors instructions mandatory requirements page limits compliance evidence', description: 'Run Pink, Red, or Gold Team findings against a frozen proposal version.', instruction: 'Review, do not silently rewrite. Organize findings by severity, location, why it matters, and recommended disposition.' },
  { key: 'citation-verification', title: 'Citation verification', phase: 'review', companyEvidence: 'optional', query: 'claims evidence citation exact numbers dates certifications commitments requirements', description: 'Verify claim support and flag partial, unsupported, or contradictory evidence.', instruction: 'Treat every claim atomically. Numbers and dates require exact support. Never accept a model-generated citation that is not in the supplied evidence set.' },
  { key: 'executive-summary', title: 'Executive summary', phase: 'proposal', companyEvidence: 'required', query: 'mission outcomes evaluation priorities success measures benefits differentiators proof', description: 'Synthesize an evaluator-focused summary from approved content and proof.', instruction: 'Introduce no new facts or commitments. Visible gaps prevent final status.' },
  { key: 'rewrite', title: 'Controlled rewrite', phase: 'proposal', companyEvidence: 'optional', query: 'requirements evaluation clarity concise persuasive tone commitments evidence', description: 'Improve selected text while preserving meaning, claims, and citation associations.', instruction: 'Add no new facts, numbers, or commitments. Describe material meaning changes and preserve evidence associations.' },
] as const;

export type AiActionKey = typeof AI_ACTIONS[number]['key'];

export function normalizeEvidenceIds(values: string[], allowedIds: ReadonlySet<string>) {
  return Array.from(new Set(values.flatMap((value) => value.toUpperCase().match(/[EC]\d+/g) ?? []).filter((value) => allowedIds.has(value))));
}
