export type ProjectRow = {
  id: string;
  owner_id: string;
  namespace: string;
  notice_id: string;
  solicitation_number: string | null;
  title: string;
  agency: string;
  department: string | null;
  naics: string | null;
  set_aside: string | null;
  place_of_performance: string | null;
  posted_at: string | null;
  response_deadline: string | null;
  source_url: string | null;
  raw_sam_json: string | null;
  status: string;
  capture_status: string;
  bid_decision: string;
  priority: string;
  estimated_value: number;
  win_probability: number;
  company_profile_id: string | null;
  template_id: string | null;
  project_manager: string | null;
  security_classification: string;
  current_amendment: number;
  latest_sam_sync_at: string | null;
  rag_status: string;
  rag_version: number;
  readiness: number;
  is_demo: number;
  created_at: string;
  updated_at: string;
};

export type DocumentRow = {
  id: string;
  owner_id: string;
  project_id: string;
  namespace: string;
  kind: string;
  title: string;
  filename: string | null;
  mime_type: string | null;
  source_url: string | null;
  storage_key: string | null;
  content_hash: string;
  content_text: string | null;
  amendment_number: number;
  supersedes_document_id: string | null;
  is_authoritative: number;
  extraction_status: string;
  page_count: number | null;
  byte_size: number;
  ingested_at: string;
  created_at: string;
};

export type ChunkRow = {
  id: string;
  owner_id: string;
  project_id: string;
  namespace: string;
  document_id: string;
  chunk_index: number;
  section: string | null;
  page_number: number | null;
  char_start: number;
  char_end: number;
  content: string;
  content_hash: string;
  vector_json: string;
  semantic_vector_json: string | null;
  embedding_model: string | null;
  amendment_number: number;
  is_superseded: number;
  created_at: string;
  document_title?: string;
};

export type RequirementRow = {
  id: string;
  owner_id: string;
  project_id: string;
  document_id: string;
  chunk_id: string;
  requirement_key: string;
  text: string;
  category: string;
  status: string;
  verification: string;
  citation_label: string;
  assignee: string | null;
  proposal_section: string | null;
  priority: string;
  due_at: string | null;
  notes: string | null;
  response_text: string | null;
  is_superseded: number;
  source_verified_at: string | null;
  amendment_number: number;
  created_at: string;
  updated_at: string;
};

export type JobRow = {
  id: string;
  owner_id: string;
  project_id: string;
  type: string;
  title: string;
  status: string;
  stage: string;
  progress: number;
  total_steps: number;
  current_step: number;
  request_json: string;
  result_json: string;
  error: string | null;
  model: string | null;
  provider_response_ids_json: string;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
};

export type ProposalRow = {
  id: string;
  owner_id: string;
  project_id: string;
  job_id: string | null;
  title: string;
  status: string;
  version: number;
  generation_mode: string;
  template_id: string | null;
  review_stage: string;
  submission_status: string;
  sections_json: string;
  citations_json: string;
  created_at: string;
  updated_at: string;
};

export type ProposalSection = {
  key: string;
  title: string;
  body: string;
  citations: Array<{ chunkId: string; label: string; quote?: string }>;
  evidenceStatus: 'cited' | 'needs-evidence';
};

export type ProfessionalAnswer = {
  headline: string;
  summary: string;
  findings: Array<{
    title: string;
    detail: string;
    severity: 'strength' | 'risk' | 'gap' | 'evidence' | 'neutral';
    citations: string[];
  }>;
  nextActions: string[];
  citations: Array<{
    id: string;
    title?: string;
    citation: string;
    excerpt: string;
    score?: number;
    chunkId: string;
    amendmentNumber?: number;
  }>;
};

export type ProjectSummary = {
  id: string;
  namespace: string;
  noticeId: string;
  solicitationNumber: string | null;
  title: string;
  agency: string;
  department: string | null;
  naics: string | null;
  setAside: string | null;
  placeOfPerformance: string | null;
  postedAt: string | null;
  responseDeadline: string | null;
  sourceUrl: string | null;
  status: string;
  captureStatus: string;
  bidDecision: string;
  priority: string;
  estimatedValue: number;
  winProbability: number;
  companyProfileId: string | null;
  templateId: string | null;
  projectManager: string | null;
  securityClassification: string;
  currentAmendment: number;
  latestSamSyncAt: string | null;
  ragStatus: string;
  ragVersion: number;
  readiness: number;
  isDemo: boolean;
  sourceCount: number;
  chunkCount: number;
  requirementCount: number;
  verifiedRequirementCount: number;
  openGapCount: number;
  latestProposalAt: string | null;
  updatedAt: string;
};
