import { env } from 'cloudflare:workers';

const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    notice_id TEXT NOT NULL,
    solicitation_number TEXT,
    title TEXT NOT NULL,
    agency TEXT NOT NULL,
    department TEXT,
    naics TEXT,
    set_aside TEXT,
    place_of_performance TEXT,
    posted_at TEXT,
    response_deadline TEXT,
    source_url TEXT,
    raw_sam_json TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    rag_status TEXT NOT NULL DEFAULT 'indexing',
    rag_version INTEGER NOT NULL DEFAULT 1,
    readiness INTEGER NOT NULL DEFAULT 0,
    is_demo INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS projects_owner_notice_unique ON projects(owner_id, notice_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS projects_owner_namespace_unique ON projects(owner_id, namespace)`,
  `CREATE INDEX IF NOT EXISTS projects_owner_updated_idx ON projects(owner_id, updated_at)`,
  `CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    filename TEXT,
    mime_type TEXT,
    source_url TEXT,
    storage_key TEXT,
    content_hash TEXT NOT NULL,
    content_text TEXT,
    amendment_number INTEGER NOT NULL DEFAULT 0,
    supersedes_document_id TEXT,
    is_authoritative INTEGER NOT NULL DEFAULT 1,
    extraction_status TEXT NOT NULL DEFAULT 'ready',
    page_count INTEGER,
    byte_size INTEGER NOT NULL DEFAULT 0,
    ingested_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS documents_project_hash_unique ON documents(owner_id, project_id, content_hash)`,
  `CREATE INDEX IF NOT EXISTS documents_project_idx ON documents(owner_id, project_id, amendment_number)`,
  `CREATE TABLE IF NOT EXISTS rag_chunks (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    document_id TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    section TEXT,
    page_number INTEGER,
    char_start INTEGER NOT NULL,
    char_end INTEGER NOT NULL,
    content TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    vector_json TEXT NOT NULL,
    amendment_number INTEGER NOT NULL DEFAULT 0,
    is_superseded INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS rag_chunks_doc_index_unique ON rag_chunks(document_id, chunk_index)`,
  `CREATE INDEX IF NOT EXISTS rag_chunks_scope_idx ON rag_chunks(owner_id, project_id, namespace, is_superseded)`,
  `CREATE TABLE IF NOT EXISTS requirements (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    document_id TEXT NOT NULL,
    chunk_id TEXT NOT NULL,
    requirement_key TEXT NOT NULL,
    text TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'General',
    status TEXT NOT NULL DEFAULT 'unreviewed',
    verification TEXT NOT NULL DEFAULT 'machine-extracted',
    citation_label TEXT NOT NULL,
    assignee TEXT,
    proposal_section TEXT,
    amendment_number INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE,
    FOREIGN KEY(chunk_id) REFERENCES rag_chunks(id) ON DELETE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS requirements_project_key_unique ON requirements(project_id, requirement_key)`,
  `CREATE INDEX IF NOT EXISTS requirements_project_status_idx ON requirements(owner_id, project_id, status)`,
  `CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    stage TEXT NOT NULL DEFAULT 'queued',
    progress INTEGER NOT NULL DEFAULT 0,
    total_steps INTEGER NOT NULL,
    current_step INTEGER NOT NULL DEFAULT 0,
    request_json TEXT NOT NULL,
    result_json TEXT NOT NULL DEFAULT '[]',
    error TEXT,
    model TEXT,
    provider_response_ids_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT,
    FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS jobs_project_updated_idx ON jobs(owner_id, project_id, updated_at)`,
  `CREATE TABLE IF NOT EXISTS proposals (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    job_id TEXT,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    version INTEGER NOT NULL DEFAULT 1,
    generation_mode TEXT NOT NULL,
    sections_json TEXT NOT NULL,
    citations_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE SET NULL
  )`,
  `CREATE INDEX IF NOT EXISTS proposals_project_updated_idx ON proposals(owner_id, project_id, updated_at)`,
  `CREATE TABLE IF NOT EXISTS rag_queries (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    query TEXT NOT NULL,
    retrieved_chunk_ids_json TEXT NOT NULL,
    answer_json TEXT NOT NULL,
    mode TEXT NOT NULL,
    model TEXT,
    provider_response_id TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS rag_queries_project_idx ON rag_queries(owner_id, project_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS audit_events (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    details_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS audit_events_owner_idx ON audit_events(owner_id, project_id, created_at)`,
] as const;

const EXTENDED_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS workspace_members (
    id TEXT PRIMARY KEY,
    workspace_owner_id TEXT NOT NULL,
    user_id TEXT,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'contributor',
    status TEXT NOT NULL DEFAULT 'invited',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS workspace_members_owner_email_unique ON workspace_members(workspace_owner_id, email)`,
  `CREATE INDEX IF NOT EXISTS workspace_members_user_idx ON workspace_members(user_id, status)`,
  `CREATE TABLE IF NOT EXISTS company_profiles (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    name TEXT NOT NULL,
    legal_name TEXT,
    uei TEXT,
    cage TEXT,
    summary TEXT NOT NULL,
    capabilities_json TEXT NOT NULL DEFAULT '[]',
    naics_json TEXT NOT NULL DEFAULT '[]',
    certifications_json TEXT NOT NULL DEFAULT '[]',
    socioeconomic_json TEXT NOT NULL DEFAULT '[]',
    differentiators_json TEXT NOT NULL DEFAULT '[]',
    contact_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'active',
    version INTEGER NOT NULL DEFAULT 1,
    is_default INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS company_profiles_owner_idx ON company_profiles(owner_id, status, updated_at)`,
  `CREATE TABLE IF NOT EXISTS company_evidence (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    profile_id TEXT NOT NULL,
    evidence_type TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    source_url TEXT,
    storage_key TEXT,
    status TEXT NOT NULL DEFAULT 'verified',
    verified_at TEXT,
    expires_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS company_evidence_profile_idx ON company_evidence(owner_id, profile_id, evidence_type, status)`,
  `CREATE TABLE IF NOT EXISTS proposal_templates (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    intent TEXT NOT NULL DEFAULT 'full',
    sections_json TEXT NOT NULL,
    instructions_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'active',
    version INTEGER NOT NULL DEFAULT 1,
    is_default INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS proposal_templates_owner_idx ON proposal_templates(owner_id, status, updated_at)`,
  `CREATE TABLE IF NOT EXISTS saved_searches (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    name TEXT NOT NULL,
    query_json TEXT NOT NULL,
    schedule TEXT NOT NULL DEFAULT 'daily',
    is_active INTEGER NOT NULL DEFAULT 1,
    last_run_at TEXT,
    next_run_at TEXT,
    last_result_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS saved_searches_owner_idx ON saved_searches(owner_id, is_active, next_run_at)`,
  `CREATE TABLE IF NOT EXISTS opportunity_leads (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    notice_id TEXT NOT NULL,
    solicitation_number TEXT,
    title TEXT NOT NULL,
    agency TEXT NOT NULL,
    naics TEXT,
    set_aside TEXT,
    posted_at TEXT,
    response_deadline TEXT,
    source_url TEXT,
    match_score INTEGER NOT NULL DEFAULT 0,
    disposition TEXT NOT NULL DEFAULT 'new',
    raw_json TEXT NOT NULL,
    discovered_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS opportunity_leads_owner_notice_unique ON opportunity_leads(owner_id, notice_id)`,
  `CREATE INDEX IF NOT EXISTS opportunity_leads_owner_deadline_idx ON opportunity_leads(owner_id, disposition, response_deadline)`,
  `CREATE TABLE IF NOT EXISTS sam_sync_events (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    status TEXT NOT NULL,
    change_type TEXT NOT NULL,
    amendment_number INTEGER NOT NULL DEFAULT 0,
    summary TEXT NOT NULL,
    before_hash TEXT,
    after_hash TEXT,
    details_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS sam_sync_events_project_idx ON sam_sync_events(owner_id, project_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS attachment_jobs (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    document_id TEXT,
    source_url TEXT NOT NULL,
    filename TEXT,
    status TEXT NOT NULL DEFAULT 'queued',
    stage TEXT NOT NULL DEFAULT 'download',
    attempts INTEGER NOT NULL DEFAULT 0,
    error TEXT,
    ocr_engine TEXT,
    table_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS attachment_jobs_project_idx ON attachment_jobs(owner_id, project_id, status, updated_at)`,
  `CREATE TABLE IF NOT EXISTS project_tasks (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'capture',
    status TEXT NOT NULL DEFAULT 'open',
    priority TEXT NOT NULL DEFAULT 'medium',
    assignee TEXT,
    due_at TEXT,
    requirement_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS project_tasks_project_idx ON project_tasks(owner_id, project_id, status, due_at)`,
  `CREATE TABLE IF NOT EXISTS pricing_items (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit TEXT NOT NULL DEFAULT 'each',
    unit_price_cents INTEGER NOT NULL DEFAULT 0,
    cost_cents INTEGER NOT NULL DEFAULT 0,
    confidence INTEGER NOT NULL DEFAULT 50,
    basis TEXT NOT NULL DEFAULT 'estimate',
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS pricing_items_project_idx ON pricing_items(owner_id, project_id, category)`,
  `CREATE TABLE IF NOT EXISTS ai_analyses (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    action_key TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    input_json TEXT NOT NULL DEFAULT '{}',
    result_json TEXT NOT NULL DEFAULT '{}',
    solicitation_chunk_ids_json TEXT NOT NULL DEFAULT '[]',
    company_evidence_ids_json TEXT NOT NULL DEFAULT '[]',
    model TEXT,
    provider_response_id TEXT,
    error TEXT,
    approved_by TEXT,
    approved_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS ai_analyses_project_idx ON ai_analyses(owner_id, project_id, action_key, updated_at)`,
  `CREATE TABLE IF NOT EXISTS proposal_revisions (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    proposal_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    title TEXT NOT NULL,
    sections_json TEXT NOT NULL,
    change_summary TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS proposal_revisions_version_unique ON proposal_revisions(proposal_id, version)`,
  `CREATE INDEX IF NOT EXISTS proposal_revisions_project_idx ON proposal_revisions(owner_id, project_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS proposal_comments (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    proposal_id TEXT NOT NULL,
    section_key TEXT,
    author_email TEXT NOT NULL,
    body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS proposal_comments_proposal_idx ON proposal_comments(owner_id, proposal_id, status, created_at)`,
  `CREATE TABLE IF NOT EXISTS proposal_approvals (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    proposal_id TEXT NOT NULL,
    stage TEXT NOT NULL,
    decision TEXT NOT NULL DEFAULT 'pending',
    approver_email TEXT NOT NULL,
    notes TEXT,
    decided_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS proposal_approvals_proposal_idx ON proposal_approvals(owner_id, proposal_id, stage, decision)`,
  `CREATE TABLE IF NOT EXISTS submission_checklist (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    proposal_id TEXT,
    label TEXT NOT NULL,
    category TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    required INTEGER NOT NULL DEFAULT 1,
    evidence TEXT,
    assignee TEXT,
    due_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS submission_checklist_project_idx ON submission_checklist(owner_id, project_id, status, category)`,
  `CREATE TABLE IF NOT EXISTS submission_packages (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    proposal_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    manifest_json TEXT NOT NULL,
    validation_json TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    submitted_at TEXT,
    submitted_by TEXT,
    outcome TEXT,
    outcome_notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS submission_packages_project_idx ON submission_packages(owner_id, project_id, status, updated_at)`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    project_id TEXT,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'info',
    is_read INTEGER NOT NULL DEFAULT 0,
    action_url TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS notifications_owner_idx ON notifications(owner_id, is_read, created_at)`,
] as const;

const CORE_COLUMN_UPGRADES = {
  projects: [
    ['capture_status', "TEXT NOT NULL DEFAULT 'qualifying'"],
    ['bid_decision', "TEXT NOT NULL DEFAULT 'pending'"],
    ['priority', "TEXT NOT NULL DEFAULT 'medium'"],
    ['estimated_value', 'INTEGER NOT NULL DEFAULT 0'],
    ['win_probability', 'INTEGER NOT NULL DEFAULT 0'],
    ['company_profile_id', 'TEXT'],
    ['template_id', 'TEXT'],
    ['project_manager', 'TEXT'],
    ['security_classification', "TEXT NOT NULL DEFAULT 'procurement-sensitive'"],
    ['current_amendment', 'INTEGER NOT NULL DEFAULT 0'],
    ['latest_sam_sync_at', 'TEXT'],
  ],
  rag_chunks: [
    ['semantic_vector_json', 'TEXT'],
    ['embedding_model', 'TEXT'],
  ],
  requirements: [
    ['priority', "TEXT NOT NULL DEFAULT 'medium'"],
    ['due_at', 'TEXT'],
    ['notes', 'TEXT'],
    ['response_text', 'TEXT'],
    ['is_superseded', 'INTEGER NOT NULL DEFAULT 0'],
    ['source_verified_at', 'TEXT'],
  ],
  proposals: [
    ['template_id', 'TEXT'],
    ['review_stage', "TEXT NOT NULL DEFAULT 'drafting'"],
    ['submission_status', "TEXT NOT NULL DEFAULT 'not-ready'"],
  ],
} as const;

let readyPromise: Promise<void> | null = null;

export function getD1(): D1Database {
  if (!env.DB) throw new Error('The D1 binding “DB” is unavailable.');
  return env.DB;
}

export async function ensureDatabase(): Promise<void> {
  if (!readyPromise) {
    readyPromise = getD1()
      .batch(SCHEMA_STATEMENTS.map((statement) => getD1().prepare(statement)))
      .then(async () => {
        for (const [table, upgrades] of Object.entries(CORE_COLUMN_UPGRADES)) {
          const info = await getD1().prepare(`PRAGMA table_info(${table})`).all<{ name: string }>();
          const existing = new Set((info.results ?? []).map((column) => column.name));
          for (const [name, definition] of upgrades) {
            if (!existing.has(name)) {
              await getD1().prepare(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`).run();
            }
          }
        }
        await getD1().batch(EXTENDED_SCHEMA_STATEMENTS.map((statement) => getD1().prepare(statement)));
      })
      .catch((error) => {
        readyPromise = null;
        throw error;
      });
  }
  await readyPromise;
}
