import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const projects = sqliteTable(
  'projects',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    namespace: text('namespace').notNull(),
    noticeId: text('notice_id').notNull(),
    solicitationNumber: text('solicitation_number'),
    title: text('title').notNull(),
    agency: text('agency').notNull(),
    department: text('department'),
    naics: text('naics'),
    setAside: text('set_aside'),
    placeOfPerformance: text('place_of_performance'),
    postedAt: text('posted_at'),
    responseDeadline: text('response_deadline'),
    sourceUrl: text('source_url'),
    rawSamJson: text('raw_sam_json'),
    status: text('status').notNull().default('active'),
    captureStatus: text('capture_status').notNull().default('qualifying'),
    bidDecision: text('bid_decision').notNull().default('pending'),
    priority: text('priority').notNull().default('medium'),
    estimatedValue: integer('estimated_value').notNull().default(0),
    winProbability: integer('win_probability').notNull().default(0),
    companyProfileId: text('company_profile_id'),
    templateId: text('template_id'),
    projectManager: text('project_manager'),
    securityClassification: text('security_classification').notNull().default('procurement-sensitive'),
    currentAmendment: integer('current_amendment').notNull().default(0),
    latestSamSyncAt: text('latest_sam_sync_at'),
    ragStatus: text('rag_status').notNull().default('indexing'),
    ragVersion: integer('rag_version').notNull().default(1),
    readiness: integer('readiness').notNull().default(0),
    isDemo: integer('is_demo', { mode: 'boolean' }).notNull().default(false),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('projects_owner_notice_unique').on(table.ownerId, table.noticeId),
    uniqueIndex('projects_owner_namespace_unique').on(table.ownerId, table.namespace),
    index('projects_owner_updated_idx').on(table.ownerId, table.updatedAt),
  ],
);

export const documents = sqliteTable(
  'documents',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    namespace: text('namespace').notNull(),
    kind: text('kind').notNull(),
    title: text('title').notNull(),
    filename: text('filename'),
    mimeType: text('mime_type'),
    sourceUrl: text('source_url'),
    storageKey: text('storage_key'),
    contentHash: text('content_hash').notNull(),
    contentText: text('content_text'),
    amendmentNumber: integer('amendment_number').notNull().default(0),
    supersedesDocumentId: text('supersedes_document_id'),
    isAuthoritative: integer('is_authoritative', { mode: 'boolean' }).notNull().default(true),
    extractionStatus: text('extraction_status').notNull().default('ready'),
    pageCount: integer('page_count'),
    byteSize: integer('byte_size').notNull().default(0),
    ingestedAt: text('ingested_at').notNull(),
    createdAt: text('created_at').notNull(),
  },
  (table) => [
    uniqueIndex('documents_project_hash_unique').on(table.ownerId, table.projectId, table.contentHash),
    index('documents_project_idx').on(table.ownerId, table.projectId, table.amendmentNumber),
  ],
);

export const ragChunks = sqliteTable(
  'rag_chunks',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    namespace: text('namespace').notNull(),
    documentId: text('document_id').notNull(),
    chunkIndex: integer('chunk_index').notNull(),
    section: text('section'),
    pageNumber: integer('page_number'),
    charStart: integer('char_start').notNull(),
    charEnd: integer('char_end').notNull(),
    content: text('content').notNull(),
    contentHash: text('content_hash').notNull(),
    vectorJson: text('vector_json').notNull(),
    semanticVectorJson: text('semantic_vector_json'),
    embeddingModel: text('embedding_model'),
    amendmentNumber: integer('amendment_number').notNull().default(0),
    isSuperseded: integer('is_superseded', { mode: 'boolean' }).notNull().default(false),
    createdAt: text('created_at').notNull(),
  },
  (table) => [
    uniqueIndex('rag_chunks_doc_index_unique').on(table.documentId, table.chunkIndex),
    index('rag_chunks_scope_idx').on(table.ownerId, table.projectId, table.namespace, table.isSuperseded),
  ],
);

export const requirements = sqliteTable(
  'requirements',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    documentId: text('document_id').notNull(),
    chunkId: text('chunk_id').notNull(),
    requirementKey: text('requirement_key').notNull(),
    text: text('text').notNull(),
    category: text('category').notNull().default('General'),
    status: text('status').notNull().default('unreviewed'),
    verification: text('verification').notNull().default('machine-extracted'),
    citationLabel: text('citation_label').notNull(),
    assignee: text('assignee'),
    proposalSection: text('proposal_section'),
    priority: text('priority').notNull().default('medium'),
    dueAt: text('due_at'),
    notes: text('notes'),
    responseText: text('response_text'),
    isSuperseded: integer('is_superseded', { mode: 'boolean' }).notNull().default(false),
    sourceVerifiedAt: text('source_verified_at'),
    amendmentNumber: integer('amendment_number').notNull().default(0),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('requirements_project_key_unique').on(table.projectId, table.requirementKey),
    index('requirements_project_status_idx').on(table.ownerId, table.projectId, table.status),
  ],
);

export const jobs = sqliteTable(
  'jobs',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    type: text('type').notNull(),
    title: text('title').notNull(),
    status: text('status').notNull().default('queued'),
    stage: text('stage').notNull().default('queued'),
    progress: integer('progress').notNull().default(0),
    totalSteps: integer('total_steps').notNull(),
    currentStep: integer('current_step').notNull().default(0),
    requestJson: text('request_json').notNull(),
    resultJson: text('result_json').notNull().default('[]'),
    error: text('error'),
    model: text('model'),
    providerResponseIdsJson: text('provider_response_ids_json').notNull().default('[]'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    completedAt: text('completed_at'),
  },
  (table) => [index('jobs_project_updated_idx').on(table.ownerId, table.projectId, table.updatedAt)],
);

export const proposals = sqliteTable(
  'proposals',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    jobId: text('job_id'),
    title: text('title').notNull(),
    status: text('status').notNull().default('draft'),
    version: integer('version').notNull().default(1),
    generationMode: text('generation_mode').notNull(),
    templateId: text('template_id'),
    reviewStage: text('review_stage').notNull().default('drafting'),
    submissionStatus: text('submission_status').notNull().default('not-ready'),
    sectionsJson: text('sections_json').notNull(),
    citationsJson: text('citations_json').notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('proposals_project_updated_idx').on(table.ownerId, table.projectId, table.updatedAt)],
);

export const ragQueries = sqliteTable(
  'rag_queries',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    namespace: text('namespace').notNull(),
    query: text('query').notNull(),
    retrievedChunkIdsJson: text('retrieved_chunk_ids_json').notNull(),
    answerJson: text('answer_json').notNull(),
    mode: text('mode').notNull(),
    model: text('model'),
    providerResponseId: text('provider_response_id'),
    createdAt: text('created_at').notNull(),
  },
  (table) => [index('rag_queries_project_idx').on(table.ownerId, table.projectId, table.createdAt)],
);

export const auditEvents = sqliteTable(
  'audit_events',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id'),
    action: text('action').notNull(),
    entityType: text('entity_type').notNull(),
    entityId: text('entity_id'),
    detailsJson: text('details_json').notNull().default('{}'),
    createdAt: text('created_at').notNull(),
  },
  (table) => [index('audit_events_owner_idx').on(table.ownerId, table.projectId, table.createdAt)],
);

export const workspaceMembers = sqliteTable(
  'workspace_members',
  {
    id: text('id').primaryKey(),
    workspaceOwnerId: text('workspace_owner_id').notNull(),
    userId: text('user_id'),
    email: text('email').notNull(),
    name: text('name').notNull(),
    role: text('role').notNull().default('contributor'),
    status: text('status').notNull().default('invited'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('workspace_members_owner_email_unique').on(table.workspaceOwnerId, table.email),
    index('workspace_members_user_idx').on(table.userId, table.status),
  ],
);

export const companyProfiles = sqliteTable(
  'company_profiles',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    name: text('name').notNull(),
    legalName: text('legal_name'),
    uei: text('uei'),
    cage: text('cage'),
    summary: text('summary').notNull(),
    capabilitiesJson: text('capabilities_json').notNull().default('[]'),
    naicsJson: text('naics_json').notNull().default('[]'),
    certificationsJson: text('certifications_json').notNull().default('[]'),
    socioeconomicJson: text('socioeconomic_json').notNull().default('[]'),
    differentiatorsJson: text('differentiators_json').notNull().default('[]'),
    contactJson: text('contact_json').notNull().default('{}'),
    status: text('status').notNull().default('active'),
    version: integer('version').notNull().default(1),
    isDefault: integer('is_default', { mode: 'boolean' }).notNull().default(false),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('company_profiles_owner_idx').on(table.ownerId, table.status, table.updatedAt)],
);

export const companyEvidence = sqliteTable(
  'company_evidence',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    profileId: text('profile_id').notNull(),
    evidenceType: text('evidence_type').notNull(),
    title: text('title').notNull(),
    summary: text('summary').notNull(),
    content: text('content').notNull(),
    metadataJson: text('metadata_json').notNull().default('{}'),
    sourceUrl: text('source_url'),
    storageKey: text('storage_key'),
    status: text('status').notNull().default('verified'),
    verifiedAt: text('verified_at'),
    expiresAt: text('expires_at'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('company_evidence_profile_idx').on(table.ownerId, table.profileId, table.evidenceType, table.status)],
);

export const proposalTemplates = sqliteTable(
  'proposal_templates',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    name: text('name').notNull(),
    description: text('description').notNull(),
    intent: text('intent').notNull().default('full'),
    sectionsJson: text('sections_json').notNull(),
    instructionsJson: text('instructions_json').notNull().default('{}'),
    status: text('status').notNull().default('active'),
    version: integer('version').notNull().default(1),
    isDefault: integer('is_default', { mode: 'boolean' }).notNull().default(false),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('proposal_templates_owner_idx').on(table.ownerId, table.status, table.updatedAt)],
);

export const savedSearches = sqliteTable(
  'saved_searches',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    name: text('name').notNull(),
    queryJson: text('query_json').notNull(),
    schedule: text('schedule').notNull().default('daily'),
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    lastRunAt: text('last_run_at'),
    nextRunAt: text('next_run_at'),
    lastResultCount: integer('last_result_count').notNull().default(0),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('saved_searches_owner_idx').on(table.ownerId, table.isActive, table.nextRunAt)],
);

export const opportunityLeads = sqliteTable(
  'opportunity_leads',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    noticeId: text('notice_id').notNull(),
    solicitationNumber: text('solicitation_number'),
    title: text('title').notNull(),
    agency: text('agency').notNull(),
    naics: text('naics'),
    setAside: text('set_aside'),
    postedAt: text('posted_at'),
    responseDeadline: text('response_deadline'),
    sourceUrl: text('source_url'),
    matchScore: integer('match_score').notNull().default(0),
    disposition: text('disposition').notNull().default('new'),
    rawJson: text('raw_json').notNull(),
    discoveredAt: text('discovered_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('opportunity_leads_owner_notice_unique').on(table.ownerId, table.noticeId),
    index('opportunity_leads_owner_deadline_idx').on(table.ownerId, table.disposition, table.responseDeadline),
  ],
);

export const samSyncEvents = sqliteTable(
  'sam_sync_events',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    status: text('status').notNull(),
    changeType: text('change_type').notNull(),
    amendmentNumber: integer('amendment_number').notNull().default(0),
    summary: text('summary').notNull(),
    beforeHash: text('before_hash'),
    afterHash: text('after_hash'),
    detailsJson: text('details_json').notNull().default('{}'),
    createdAt: text('created_at').notNull(),
  },
  (table) => [index('sam_sync_events_project_idx').on(table.ownerId, table.projectId, table.createdAt)],
);

export const attachmentJobs = sqliteTable(
  'attachment_jobs',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    documentId: text('document_id'),
    sourceUrl: text('source_url').notNull(),
    filename: text('filename'),
    status: text('status').notNull().default('queued'),
    stage: text('stage').notNull().default('download'),
    attempts: integer('attempts').notNull().default(0),
    error: text('error'),
    ocrEngine: text('ocr_engine'),
    tableCount: integer('table_count').notNull().default(0),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    completedAt: text('completed_at'),
  },
  (table) => [index('attachment_jobs_project_idx').on(table.ownerId, table.projectId, table.status, table.updatedAt)],
);

export const projectTasks = sqliteTable(
  'project_tasks',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull().default(''),
    category: text('category').notNull().default('capture'),
    status: text('status').notNull().default('open'),
    priority: text('priority').notNull().default('medium'),
    assignee: text('assignee'),
    dueAt: text('due_at'),
    requirementId: text('requirement_id'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('project_tasks_project_idx').on(table.ownerId, table.projectId, table.status, table.dueAt)],
);

export const pricingItems = sqliteTable(
  'pricing_items',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    category: text('category').notNull(),
    description: text('description').notNull(),
    quantity: integer('quantity').notNull().default(1),
    unit: text('unit').notNull().default('each'),
    unitPriceCents: integer('unit_price_cents').notNull().default(0),
    costCents: integer('cost_cents').notNull().default(0),
    confidence: integer('confidence').notNull().default(50),
    basis: text('basis').notNull().default('estimate'),
    notes: text('notes'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('pricing_items_project_idx').on(table.ownerId, table.projectId, table.category)],
);

export const aiAnalyses = sqliteTable(
  'ai_analyses',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    actionKey: text('action_key').notNull(),
    title: text('title').notNull(),
    status: text('status').notNull().default('queued'),
    inputJson: text('input_json').notNull().default('{}'),
    resultJson: text('result_json').notNull().default('{}'),
    solicitationChunkIdsJson: text('solicitation_chunk_ids_json').notNull().default('[]'),
    companyEvidenceIdsJson: text('company_evidence_ids_json').notNull().default('[]'),
    model: text('model'),
    providerResponseId: text('provider_response_id'),
    error: text('error'),
    approvedBy: text('approved_by'),
    approvedAt: text('approved_at'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('ai_analyses_project_idx').on(table.ownerId, table.projectId, table.actionKey, table.updatedAt)],
);

export const proposalRevisions = sqliteTable(
  'proposal_revisions',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    proposalId: text('proposal_id').notNull(),
    version: integer('version').notNull(),
    title: text('title').notNull(),
    sectionsJson: text('sections_json').notNull(),
    changeSummary: text('change_summary').notNull(),
    createdBy: text('created_by').notNull(),
    createdAt: text('created_at').notNull(),
  },
  (table) => [
    uniqueIndex('proposal_revisions_version_unique').on(table.proposalId, table.version),
    index('proposal_revisions_project_idx').on(table.ownerId, table.projectId, table.createdAt),
  ],
);

export const proposalComments = sqliteTable(
  'proposal_comments',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    proposalId: text('proposal_id').notNull(),
    sectionKey: text('section_key'),
    authorEmail: text('author_email').notNull(),
    body: text('body').notNull(),
    status: text('status').notNull().default('open'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('proposal_comments_proposal_idx').on(table.ownerId, table.proposalId, table.status, table.createdAt)],
);

export const proposalApprovals = sqliteTable(
  'proposal_approvals',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    proposalId: text('proposal_id').notNull(),
    stage: text('stage').notNull(),
    decision: text('decision').notNull().default('pending'),
    approverEmail: text('approver_email').notNull(),
    notes: text('notes'),
    decidedAt: text('decided_at'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('proposal_approvals_proposal_idx').on(table.ownerId, table.proposalId, table.stage, table.decision)],
);

export const submissionChecklist = sqliteTable(
  'submission_checklist',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    proposalId: text('proposal_id'),
    label: text('label').notNull(),
    category: text('category').notNull(),
    status: text('status').notNull().default('open'),
    required: integer('required', { mode: 'boolean' }).notNull().default(true),
    evidence: text('evidence'),
    assignee: text('assignee'),
    dueAt: text('due_at'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('submission_checklist_project_idx').on(table.ownerId, table.projectId, table.status, table.category)],
);

export const submissionPackages = sqliteTable(
  'submission_packages',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id').notNull(),
    proposalId: text('proposal_id').notNull(),
    status: text('status').notNull().default('draft'),
    manifestJson: text('manifest_json').notNull(),
    validationJson: text('validation_json').notNull(),
    contentHash: text('content_hash').notNull(),
    submittedAt: text('submitted_at'),
    submittedBy: text('submitted_by'),
    outcome: text('outcome'),
    outcomeNotes: text('outcome_notes'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('submission_packages_project_idx').on(table.ownerId, table.projectId, table.status, table.updatedAt)],
);

export const notifications = sqliteTable(
  'notifications',
  {
    id: text('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    projectId: text('project_id'),
    type: text('type').notNull(),
    title: text('title').notNull(),
    message: text('message').notNull(),
    severity: text('severity').notNull().default('info'),
    isRead: integer('is_read', { mode: 'boolean' }).notNull().default(false),
    actionUrl: text('action_url'),
    createdAt: text('created_at').notNull(),
  },
  (table) => [index('notifications_owner_idx').on(table.ownerId, table.isRead, table.createdAt)],
);
